[package]
name = "mq-tactical-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.21.0"
egui-macroquad = "0.15.0"
macroquad = "0.3.25"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.119"
